# Generated by Django 3.2.2 on 2021-05-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NTOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=2048, unique=True)),
                ('OrderSellerID', models.IntegerField()),
                ('OriginID', models.IntegerField()),
                ('Sku', models.IntegerField()),
                ('Description', models.CharField(max_length=2048)),
                ('Quantity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('Value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('CategoryIDSeller', models.IntegerField(blank=True, null=True)),
                ('legal_name', models.CharField(max_length=2048)),
                ('siteLink', models.URLField(max_length=4096)),
                ('ecommerce_url', models.URLField(max_length=4096)),
            ],
        ),
    ]
